// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCql87wqrys3GsaxV6sr1dJ43yf4X_3mUs',
    appId: '1:1011634961119:web:9e7cba5120f6b970c7c76a',
    messagingSenderId: '1011634961119',
    projectId: 'fitnova-dba8d',
    authDomain: 'fitnova-dba8d.firebaseapp.com',
    storageBucket: 'fitnova-dba8d.firebasestorage.app',
    measurementId: 'G-YC7X3N1E1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkj7Nr_N6zhDBr3Uk35g-4lML6MZxpq2U',
    appId: '1:1011634961119:android:a984f0303abc06ecc7c76a',
    messagingSenderId: '1011634961119',
    projectId: 'fitnova-dba8d',
    storageBucket: 'fitnova-dba8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAocCkEUS-9N6WT7FWWY12YVk8jcsmOoIA',
    appId: '1:1011634961119:ios:76c198d10f90d7c8c7c76a',
    messagingSenderId: '1011634961119',
    projectId: 'fitnova-dba8d',
    storageBucket: 'fitnova-dba8d.firebasestorage.app',
    iosBundleId: 'com.example.fitnovaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAocCkEUS-9N6WT7FWWY12YVk8jcsmOoIA',
    appId: '1:1011634961119:ios:76c198d10f90d7c8c7c76a',
    messagingSenderId: '1011634961119',
    projectId: 'fitnova-dba8d',
    storageBucket: 'fitnova-dba8d.firebasestorage.app',
    iosBundleId: 'com.example.fitnovaa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCql87wqrys3GsaxV6sr1dJ43yf4X_3mUs',
    appId: '1:1011634961119:web:9ad5f0f09302c628c7c76a',
    messagingSenderId: '1011634961119',
    projectId: 'fitnova-dba8d',
    authDomain: 'fitnova-dba8d.firebaseapp.com',
    storageBucket: 'fitnova-dba8d.firebasestorage.app',
    measurementId: 'G-1MYTNF6V54',
  );
}
